a2=A2
a2b=2B
a9s=9S
rbot9s=Strange Machine Lifeform
pod042=Pod 042
pod153=Pod 153
pod042_153=Pod 042 / Pod 153
cmd=Commander
pascal=Pascal
adam=Adam
eve=Eve
eml=Emil
emls=Emil Mob
ppl=Popola
dbl=Devola
op60=Operator 6O
op210=Operator 21O
210=Operator 21O
ane=Anemone
girls=Red Girls
girlA=Red Girl A
girlB=Red Girl B
jackas=Jackass
js=Jackass
ys=YoRHa Soldier
ysA=YoRHa Soldier
ysB=YoRHa Soldier
yall=YoRHa Soldiers
bys=Armed YoRHa Soldiers
pollutions=Contaminated YoRHa
a4b=4B
a12h=12H
a1d=1D
a11b=11B
a11s=11S
a7b=7B
16d=16D
a3b=3B
a1b=1B
a9b=9B
a6b=6B
a5b=5B
n4=Number 4
yolhaS=YoRHa S-Type
op=Operator
opa=Operator
opb=Operator
bcast=Internal Broadcast
bankcast=Bunker PA System
bs=Maintenance Shop Owner
adjuster=Maintenance Shop Owner
resistance=Resistance Member
resi=Resistance Member
resiwomanA=Resistance Member
resiwomanB=Resistance Member
resimanA=Resistance Member
resiman=Resistance Member
resiwoman=Resistance Member
resiwoman2=Resistance Member
hennawresi=Strange Resistance Woman
hennamresi=Strange Resistance Man
jukeBox=Jukebox
manager=Manager
kj=Weapons Trader
toolshop=Supply Trader
ysE=YoRHa E-Type
tani=Canyon Robo
robobusy=High-speed Robo
hugeRobo=Giant Robo
robomaster=Robo-Master
lostway=Lost Robo
kenjarobo=Wise Robo
a8b=8B
22b=22B
64b=64B
robot_wife=Wife Robo
loverobo=Robot in Love
sp=Supply Trader
robomask=Masked Robo
robomaskrece=Masked Receptionist
robomaskmode=Masked Chairman
dranker1=YoRHa Soldier
dranker2=YoRHa Soldier
dragshop=YoRHa Soldier
chosareji=Resistance Researcher
dreamrobo=Robot with a Dream
roboshop=Shopkeeper Robot
robocreator=Game Creator Robo
jyuri1=Juliet 1
jyuri2=Juliet 2
jyuri3=Juliet 3
romi1=Romeo 1
romi2=Romeo 2
romi3=Romeo 3
robobro=Older Brother Robo
Youngbro=Younger Brother Robo
uraguchi=Back Entrance Robo
kyukei=Robot on a Break
robomama=Robo Mama
amusechildren=Robo Children
robopapa=Robo Papa
pierobo=Clown Robo
actionrobo=Active Robo
robocry=Crying Robot
roborece=Robo Receptionist
roboeerie=Creepy Robot
roboyell=Revved-up Robot
robosmail=Laughing Robot
robokiller=Angry Robot
robozombie=Zombie Robot
zonbirobo=Robo Zombie
audience=Audience
rabit=Rabbit Machine
husenani=Balloon Younger Brother
husenoto=Balloon Apprentice
husenane=Balloon Older Sister
husenimo=Balloon Younger Sister
robos=Machine Lifeforms
robochild=Child Robo
child=Child Robo
robochildrenA=Child Robo
robochildrenB=Child Robo
robochildren=Children Robos
children=Children Robos
kjrobo=Weapons Trader Robo
indoor=Indoor Robo
outdoor=Outdoor Robo
ballrobo=Ball-like Robo
yasashi=Friendly Robo
kokourobo=Lonely Robo
hakorobo=Sheltered Robo
makerobo=Robo with Makeup
donaga=Tall Robo
pickuprobo=Excited Robo
hashirobo=Robo on Edge
jishinrobo=Simple Robo
asobitai=Cheerful Robo
asobitasugi=Too Playful Robo
asobisuki=Playful Robo
mihari=Guard Robo
guide=Distracted Robo
srobo=Small Robo
ssrobo=Smaller Robo
giant=Big Robo
robomother=Overprotective Robo
hickey=Son Robo
mama=Robo Mother
papa=Robo Father
sarutoru=Sartre
jean=Jean-Paul
hatrobo=Robo with Hat
villager=Normal Robo
normalrobo=Normal Robo
sister=Older Sister Robo
youngsister=Younger Sister Robo
ribonrobo=Robo with Ribbon
talkrobo=Weird-talking Robo
robotoolshop=Tool Shop Robo
robophd=Scientist Robo
friendrobo=Friend Robo
floatfriend=Distracted Friend Robo
robostrange=Weird Robo
roboA=Machine Lifeform A
roboB=Machine Lifeform B
forestkj=Forest Blacksmith
masamune=Masamune
roboGK=Gatekeeper Robo
robomode=Robo Chairman
animallike=Animal-loving Robo
hakamori=Gravekeeper Robo
kdc=Knight Captain
all=All
core=Core
largerobot=Big Machine Lifeform
smallrobot=Small Machine Lifeform
resiitem=Resistance Supply Trader
4s=4S
andmys=Gatekeeper
reception=Receptionist
moderator=MC
cap=Aircraft Carrier Captain
prst=Priest
prsts=Priests
believer=Believer
obiebeliev=Scared Believer
believts=Supply Trading Believer
osoware=Attacked Believer
floatchild=Distracted Child Machine
facannounce=Factory PA
robo=Small Robo
smachine=Minor Enemy Machine
lmachine=Boss Enemy Machine
n02=Machine Lifeform
apolorobo=Apologetic Robo
vw=Beauvoir
simone=Simone
eng=Engels
spider=Spider Boss
robosmallgold=Courageous Older Brother
robosmallgoldwoman=Hateful Younger Sister
robolargegoldcchild=Vengeful Son
robolargegold=Gold Large-Scale Weapon Biped
announce=Tower System Service
sele=<Selection>
man=Man
human=Man
sku=Resource Recovery Unit
ttl=Title
telo=Subtitle
servermanager=Server Manager
system=System
unknown=-
noname=???
humconference=Council of Humanity
plato=Plato 1728
maskshop=Masked Trader
unknownletter=[Anonymous]
secretary=Resistance Secretary
teruterubozu=Mysterious Object
dreamR1=Dreamer Robo
dreamR2=Friend Robo
restR=Robo on a Break
terminalR=Operator Robo
watchR=Guard Robo
lookR=Observing Robo
attractR=Interested Robo
frightenedR=Scared Robo
encourageR=Encouraging Robo
audienceR=Spectator Robo
questionR=Intrigued Robo
duskR=Melancholic Robo
badR=Foul-mouthed Robo
difficultR=Troubled Robo
enthusiasticR=Enthusiastic Robo
childR=Child Robo
bossR=Boss Robo
subordinateR=Subordinate Robo
bossR2=Former Boss Robo
subordinateR2=Former Subordinate Robo
loafR2=Loafing Robo
putR=Cleaning Robo
juniorR=Kouhai Robo
suspiciousA=Suspicious Android
