M3010_S0080_G0000_001_a2=This place...
M3010_S0080_G0010_001_pod042=A2's memory space appears to have been damaged by hacking due to the impact of the EMP attack.
M3010_S0080_G0020_001_a2=So this is my memory area...
M3010_S0080_G0030_001_a2=But then, why are you here?
M3010_S0080_G0040_001_pod042=Accompanying support units are obligated to perform internal monitoring when their support target develops a malfunction.
M3010_S0080_G0050_001_a2=Don't just barge into my head whenever you feel like it...
M3010_S0080_G0060_001_a2=Gh...
M3010_S0080_G0070_001_n02=I... am... Desert... Prototype...
M3010_S0080_G0080_001_n02=Created... to exterminate mankind...
M3010_S0080_G0090_001_a2=What is... this?
M3010_S0080_G0100_001_pod042=Hacking by an enemy unit is forcibly merging this space with the enemy's memory space.
M3010_S0080_G0110_001_cmd=Originally... we should call you... but... 2B and...
M3010_S0080_G0120_001_cmd=Continue surveillance, and depending on the situation, dispose of her...
M3010_S0080_G0130_001_pod042=This data is a fragment of 2B's memory data.
M3010_S0080_G0140_001_pod042=An order she received from the YoRHa Commander while alive.
M3010_S0080_G0150_001_n4=...That's wrong, Number Two. We all... chose... to come here...
M3010_S0080_G0160_001_n4=Thank you... for giving me a reason to live...
M3010_S0080_G0170_001_a2=Stop it!!!
M3010_S0080_G0180_001_pod042=This data is recognized as YoRHa Unit A2's own memories.
M3010_S0080_G0190_001_a2=Shut up! Just cut the connection already!!
M3010_S0080_G0200_001_n02=Mama... Mama...
M3010_S0080_G0210_001_n02=Mama...
