M6010_S0010_G0000_300_cmd=You two, what happened to your mission? I already sent you the destination data.
M6010_S0010_G0010_300_cmd=How long do you intend to stand there? Do not forget our purpose.
M6010_S0010_G0020_300_op60=Good work out there! How are you feeling?
M6010_S0010_G0030_300_op60=Pretty flowers, big trees, cute animals... It all sounds so nice...
M6010_S0010_G0040_300_op60=Um, is something wrong? Did I maybe forget to send you the intel...?
M6010_S0010_G0050_300_op60=What should I do... I'm going to get yelled at again...
M6010_S0010_G0060_300_op210=Do you need something? Please keep it brief.
M6010_S0010_G0070_300_op210=Are you still here? Please return to your mission immediately.
M6010_S0010_G0080_300_op210=I will report this as a violation of orders.
M6010_S0010_G1230_300_bs=Leave unit maintenance to me.
M6010_S0010_G1240_300_bs=You would like maintenance, correct?
M6010_S0010_G1250_300_bs=Even among Scanner models, my skills are first-class. You may rely on me.
M6010_S0020_G0000_300_cmd=What is it? Has something gone wrong?
M6010_S0020_G0010_300_cmd=If nothing is wrong, then fine. Continue your mission.
M6010_S0020_G0020_300_cmd=Is the mission going smoothly?
M6010_S0020_G0030_300_op60=Welcome back! Hey, hey, show me the new surface data!
M6010_S0020_G0040_300_op60=Hmm, I see............
M6010_S0020_G0050_300_op210=What brings you here today?
M6010_S0020_G0060_300_op210=Analysis of the Alien Alert... is not progressing very well.
M6010_S0020_G0070_300_op210=My interest in the surface never ends. I have no desire to go there in person, though...
M6010_S0020_G0080_300_op210=I am an Operator model, so I feel calmest when I am looking at data like this.
M6010_S0020_G1230_300_bs=Leave maintenance to me. What shall we enhance today?
M6010_S0030_G0000_300_cmd=Any contact from the surface, no matter how minor, is to be reported immediately!
M6010_S0030_G0010_300_cmd=...You two, what are you doing here?
M6010_S0030_G0020_300_cmd=This is an emergency. Head to the site immediately.
M6010_S0030_G0030_300_op60=Huh? You two are supposed to be on the surface right now...\nThis is bad! I don't want to report you for violating orders!
M6010_S0030_G0040_300_op60=What are you doing!? Please return to the operation at once!
M6010_S0030_G0050_300_op210=...Why are you here? You should have been assigned a mission on the surface.
M6010_S0030_G0060_300_op210=Being here is a violation of orders.
M6010_S0030_G0070_300_op210=You should not be here right now. Return to your mission immediately.
M6010_S0040_G0000_300_cmd=2B... I'm glad you're safe.
M6010_S0040_G0010_300_cmd=We still cannot contact several of our comrades from the operation. ...Sorry, but please hurry and begin the search.
M6010_S0040_G0020_300_cmd=The damage this time is severe. If another one of those things appears... we will have trouble...
M6010_S0040_G0030_300_op60=I'm sorry... I still haven't obtained any information on 9S...
M6010_S0040_G0040_300_op60=2B, please don't be reckless.
M6010_S0040_G0050_300_op210=Operator 21O to 9S. ...9S, respond.
M6010_S0040_G0060_300_op210=...Repeating. Operator 21O to 9S... Respond...
M6010_S0050_G0000_300_cmd=9S! 2B has fallen into an enemy trap! Provide support at once!
M6010_S0050_G0010_300_cmd=I am counting on you to save 2B...
M6010_S0050_G0020_300_op60=9S, please... 2B...
M6010_S0050_G0030_300_op60=2B... Please be safe...
M6010_S0050_G0040_300_op210=...Go out into the corridor, and you will find the Server Management Room opposite the Command Room.
M6010_S0050_G0050_300_op210=From there, you should be able to act on the surface remotely.
M6010_S0050_G0060_300_op210=Excessive activity immediately after repairs is not recommended. Please refrain from reckless behavior.
M6010_S0060_G0000_300_cmd=All YoRHa units, take combat positions! Report anything from the surface immediately!!
M6010_S0060_G0010_300_cmd=Dammit... What's happening...?
M6010_S0060_G0020_300_op60=I'm so glad you're safe...
M6010_S0060_G0030_300_op60=Communications with the surface are extremely unstable right now.\nPlease don't be too reckless, okay?
M6010_S0060_G0040_300_op60=Be careful...!
M6010_S0060_G0050_300_op210=...You have a tendency toward reckless behavior. Please be very careful.
M6010_S0060_G0060_300_op210=...Be careful.
M6010_S0070_G0070_300_cmd=The operation is going smoothly, but do not let your guard down.
M6010_S0070_G0080_300_cmd=We have existed for this day. Show me your worth.
M6010_S0070_G0090_300_cmd=This operation must succeed.
M6010_S0070_G0100_300_op60=Hey! What about your mission!? You are going to get in trouble for violating orders!
M6010_S0070_G0110_300_op60=Hey! Are you still here!? Hurry to the surface already!
M6010_S0070_G0120_300_op60=I have to cover for you with the Commander...
M6010_S0070_G0130_300_op210=Why have you come here? Is there a problem?
M6010_S0070_G0140_300_op210=Once you are ready, please return to your mission.
M6011_S0021_G1240_300_bs=You would like maintenance, correct?
M6012_S0022_G1250_300_bs=If you ever feel your unit lacks performance, come see me anytime.
